eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  instance:
    hostname: "${HOSTNAME}.eureka"
    secure-port-enabled: true
    non-secure-port-enabled: false
server:
    port: 8761
    ssl:
      enabled: true
      key-alias: relevebancaire-docker
      key-store: classpath:relevebancaire-docker-keystore.p12
      key-store-password: secret
      key-store-type: PKCS12
